[build]
  base = "TobiasWuki/beaBall2024"                # Basisverzeichnis für den Build-Prozess
  publish = "public"          # Verzeichnis, das veröffentlicht werden soll
  command = "npm run build"   # Build-Befehl
